#!/usr/bin/env bun
// Auto-generated by /init — do not edit.
// Finds the latest active dev-core plugin in the cache and runs the issues dashboard.
// Survives plugin updates without re-running /init.
import { readdirSync, existsSync, statSync } from 'fs'
import { homedir } from 'os'
import { join } from 'path'

const base = join(homedir(), '.claude/plugins/cache/roxabi-marketplace/dev-core')
const dirs = readdirSync(base).filter(
  d => !d.startsWith('.') && !existsSync(join(base, d, '.orphaned_at'))
)
if (!dirs.length) throw new Error('dev-core not found in plugin cache. Run: claude plugin install dev-core')
const latest = dirs.sort((a, b) => statSync(join(base, b)).mtimeMs - statSync(join(base, a)).mtimeMs)[0]
await import(join(base, latest, 'skills/issues/dashboard.ts'))
