#!/usr/bin/env bash
# Install the repo git hooks (pre-commit + pre-push, via the pre-commit
# framework) into the EFFECTIVE hooks directory.
#
# Why not `pre-commit install`: it refuses to run whenever core.hooksPath is
# set at ANY scope ("Cowardly refusing…"), and this machine sets it both
# globally (ccc reindex hooks) and repo-locally — which is how the repo ended
# up with pre-push-stage hooks in .pre-commit-config.yaml but no pre-push
# hook installed, i.e. those gates never ran. This script writes the same
# `pre-commit hook-impl` dispatcher wrappers `pre-commit install` would have
# written, directly into the effective hooks dir, and installs ccc post-merge/post-rewrite/post-checkout via ~/projects/scripts/git-hooks/install-ccc-hooks.sh.
#
# Idempotent — safe to re-run; invoked by `make install` (hooks live in the
# shared common hooks dir, so one install covers the main checkout and every
# linked worktree).
#
# Caveats: any pre-existing non-generated hook of the managed types
# (pre-commit/pre-push/post-merge/post-rewrite/post-checkout) is REPLACED on each run — no
# `.legacy` preservation (divergence from `pre-commit install`, accepted for
# this fleet). If the repo directory moves/renames, re-run this script: the
# pinned absolute core.hooksPath goes stale silently.
set -euo pipefail

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$REPO_ROOT"

if ! command -v pre-commit >/dev/null 2>&1 && [[ ! -x .venv/bin/pre-commit ]]; then
  echo "install-hooks: pre-commit not found — install it (e.g. 'uv tool install pre-commit', or 'uv sync' for .venv/bin/pre-commit) and re-run" >&2
  exit 2
fi

# Resolve the hooks dir from the REPO-LOCAL scope only. On a machine where
# core.hooksPath is set globally but not locally, the merged value would point
# at the GLOBAL hooks dir — and writing this repo's dispatchers there would
# fire its quality gates in EVERY repo on the machine. Never write outside the
# repo: fall back to the common hooks dir and pin it with a local override
# (the global chain-through below keeps the global hooks alive).
hooks_dir="$(git config --local core.hooksPath || true)"
if [[ -z "$hooks_dir" ]]; then
  hooks_dir="$(git rev-parse --path-format=absolute --git-common-dir)/hooks"
  if [[ -n "$(git config --global core.hooksPath || true)" ]]; then
    git config core.hooksPath "$hooks_dir"
    echo "install-hooks: global core.hooksPath detected — pinned repo-local hooksPath to ${hooks_dir}"
  fi
fi
mkdir -p "$hooks_dir"

# Generated hooks resolve every path at RUNTIME. The heredocs use a quoted
# delimiter so NOTHING expands at write time — a quote/`$()`-bearing checkout
# path can never bake a live command substitution into a hook that then runs
# on every commit. The only injected token is the hook-type literal (a fixed,
# safe value from the calls below), substituted via sed on a placeholder.
write_dispatcher() {
  local hook_type="$1"
  sed "s/@HOOK_TYPE@/${hook_type}/g" >"${hooks_dir}/${hook_type}" <<'EOF'
#!/usr/bin/env bash
# Generated by tools/install-hooks.sh — do not edit; re-run the script instead.
here="$(cd "$(dirname "$0")" && pwd)"
if command -v pre-commit >/dev/null 2>&1; then
  exec pre-commit hook-impl --config=.pre-commit-config.yaml --hook-type=@HOOK_TYPE@ --hook-dir "$here" -- "$@"
elif [ -x .venv/bin/pre-commit ]; then
  # pre-commit may live only in the uv dev group — git runs hooks from the
  # worktree top, so the repo-relative venv is correct (and per-worktree).
  exec .venv/bin/pre-commit hook-impl --config=.pre-commit-config.yaml --hook-type=@HOOK_TYPE@ --hook-dir "$here" -- "$@"
fi
echo "pre-commit not found — refusing to skip quality gates silently." >&2
echo "Fix: uv tool install pre-commit  or  uv sync (provides .venv/bin/pre-commit); bypass once with --no-verify" >&2
exit 1
EOF
  chmod +x "${hooks_dir}/${hook_type}"
  echo "install-hooks: wrote ${hooks_dir}/${hook_type}"
}

write_dispatcher pre-commit
write_dispatcher pre-push

# ccc reindex after pull / rebase / branch switch (shared installer).
# Delegates to scripts/git-hooks/install-ccc-hooks.sh (post-merge + post-rewrite + post-checkout).
INSTALL_CCC="${CCC_HOOKS_INSTALL:-$HOME/projects/scripts/git-hooks/install-ccc-hooks.sh}"
if [[ -x "$INSTALL_CCC" ]]; then
  "$INSTALL_CCC" "$(git rev-parse --show-toplevel)" || true
else
  echo "install-hooks: skip ccc hooks (missing $INSTALL_CCC)" >&2
fi

echo "install-hooks: done (hooks dir: ${hooks_dir})"
