#!/usr/bin/env bash
# Install the repo git hooks (pre-commit + pre-push, via the pre-commit
# framework) into the EFFECTIVE hooks directory.
#
# Why not `pre-commit install`: it refuses to run whenever core.hooksPath is
# set at ANY scope ("Cowardly refusing…"), and this machine sets it both
# globally (ccc reindex hooks) and repo-locally — which is how the repo ended
# up with pre-push-stage hooks in .pre-commit-config.yaml but no pre-push
# hook installed, i.e. those gates never ran. This script writes the same
# `pre-commit hook-impl` dispatcher wrappers `pre-commit install` would have
# written, directly into the effective hooks dir, and re-chains any global
# hooks (ccc post-merge / post-rewrite) that a repo-local core.hooksPath
# override shadows.
#
# Idempotent — safe to re-run; invoked by `make install` (hooks live in the
# shared common hooks dir, so one install covers the main checkout and every
# linked worktree).
set -euo pipefail

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$REPO_ROOT"

if ! command -v pre-commit >/dev/null 2>&1; then
  echo "install-hooks: pre-commit not found — install it (e.g. 'uv tool install pre-commit') and re-run" >&2
  exit 2
fi

# Resolve the hooks dir from the REPO-LOCAL scope only. On a machine where
# core.hooksPath is set globally but not locally, the merged value would point
# at the GLOBAL hooks dir — and writing this repo's dispatchers there would
# fire its quality gates in EVERY repo on the machine. Never write outside the
# repo: fall back to the common hooks dir and pin it with a local override
# (the global chain-through below keeps the global hooks alive).
hooks_dir="$(git config --local core.hooksPath || true)"
if [[ -z "$hooks_dir" ]]; then
  hooks_dir="$(git rev-parse --path-format=absolute --git-common-dir)/hooks"
  if [[ -n "$(git config --global core.hooksPath || true)" ]]; then
    git config core.hooksPath "$hooks_dir"
    echo "install-hooks: global core.hooksPath detected — pinned repo-local hooksPath to ${hooks_dir}"
  fi
fi
mkdir -p "$hooks_dir"

write_dispatcher() {
  local hook_type="$1"
  cat >"${hooks_dir}/${hook_type}" <<EOF
#!/usr/bin/env bash
# Generated by tools/install-hooks.sh — do not edit; re-run the script instead.
if ! command -v pre-commit >/dev/null 2>&1; then
  echo "pre-commit not found — refusing to skip quality gates silently." >&2
  echo "Fix: uv tool install pre-commit  (or bypass once with --no-verify)" >&2
  exit 1
fi
exec pre-commit hook-impl --config=.pre-commit-config.yaml --hook-type=${hook_type} --hook-dir "${hooks_dir}" -- "\$@"
EOF
  chmod +x "${hooks_dir}/${hook_type}"
  echo "install-hooks: wrote ${hooks_dir}/${hook_type}"
}

write_dispatcher pre-commit
write_dispatcher pre-push

# A repo-local core.hooksPath shadows the global hooks dir entirely — re-chain
# any executable global hooks (post-merge/post-rewrite ccc reindex) so setting
# a local hooksPath doesn't silently disable them.
global_dir="$(git config --global core.hooksPath || true)"
if [[ -n "$global_dir" && "$global_dir" != "$hooks_dir" ]]; then
  for hook_type in post-merge post-rewrite; do
    if [[ -x "${global_dir}/${hook_type}" ]]; then
      cat >"${hooks_dir}/${hook_type}" <<EOF
#!/usr/bin/env bash
# Generated by tools/install-hooks.sh — chains the global ${hook_type} hook
# that the repo-local core.hooksPath override would otherwise shadow.
exec "${global_dir}/${hook_type}" "\$@"
EOF
      chmod +x "${hooks_dir}/${hook_type}"
      echo "install-hooks: chained global ${hook_type} → ${global_dir}/${hook_type}"
    fi
  done
fi

echo "install-hooks: done (hooks dir: ${hooks_dir})"
