name: publish
on:
  push:
    branches: [staging]
    tags: ['voicecli/v*']
permissions:
  contents: read
  packages: write
jobs:
  publish:
    uses: Roxabi/.github/.github/workflows/publish-container.yml@v1
    with:
      image_name: ghcr.io/roxabi/voicecli
      release_please_component: voicecli

  publish-mock:
    uses: Roxabi/.github/.github/workflows/publish-container.yml@v1
    with:
      image_name: ghcr.io/roxabi/voicecli-mock
      dockerfile_path: Dockerfile.mock
      release_please_component: voicecli
